const STORE_KEY="lapetite.staff.v1", AUTH_KEY="lapetite.staff.auth", PIN="Ahodwo2026";
const CATEGORIES=["Pharmacist","Pharmacy Technician","MCA","Administration","Accounting","Other"];
const STATUSES=["Full-time","Part-time","Temporary","Probation","Casual","Other"];
const EDUCATION=["JHS / BECE","SHS / WASSCE","Certificate","Diploma","HND","Bachelor’s Degree","Postgraduate / Master’s","Other"];
const MARITAL=["Single","Married","Divorced","Widowed"];
const DOCS=["Ghana Card (front and back)","Certificates / licences","Passport photograph","Curriculum vitae"];
const STEPS=[{id:"personal",title:"Personal"},{id:"family",title:"Family"},{id:"education",title:"Education"},{id:"employment",title:"Employment"},{id:"payment",title:"Identification"},{id:"contacts",title:"Contacts"},{id:"medical",title:"Medical & notes"}];
const blankEmployee=()=>({id:"",staffNo:"",firstName:"",middleName:"",lastName:"",dob:"",phone:"",altPhone:"",marital:"",children:"",address:"",digitalAddress:"",email:"",motherName:"",fatherName:"",education:"",educationOther:"",course:"",institution:"",jobTitle:"",startDate:"",status:"Full-time",statusOther:"",qualification:"",awardingBody:"",category:"Pharmacy Technician",categoryOther:"",licenceNo:"",licenceExpiry:"",ghanaCard:"",ssnit:"",bankName:"",bankBranch:"",accountName:"",accountNo:"",em1Name:"",em1Rel:"",em1Phone:"",em1Address:"",em2Name:"",em2Rel:"",em2Phone:"",em2Address:"",kinName:"",kinRel:"",kinPhone:"",kinAddress:"",allergies:"",medical:"",hospital:"",bloodGroup:"",notes:"",documents:[],branch:"Ahodwo, Kumasi",createdAt:"",updatedAt:"",declared:false});
function seedEmployees(){return [];}
function loadAll(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw){const s=seedEmployees();saveAll(s);return s;}return JSON.parse(raw);}catch{return [];}}
function saveAll(list){localStorage.setItem(STORE_KEY,JSON.stringify(list));}
let employees=loadAll(), view="dashboard", editingId=null, stepIndex=0, draft=blankEmployee(), filters={q:"",category:"",status:""};
const $=id=>document.getElementById(id);
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400);}
function fullName(e){return [e.firstName,e.middleName,e.lastName].filter(Boolean).join(" ");}
function initials(e){return ((e.firstName||"?")[0]+(e.lastName||"?")[0]).toUpperCase();}
function daysUntil(dateStr){if(!dateStr)return null;return Math.round((new Date(dateStr+"T00:00:00")-new Date())/86400000);}
function licenceBadge(e){const d=daysUntil(e.licenceExpiry);if(d===null)return '<span class="badge badge-muted">No licence</span>';if(d<0)return '<span class="badge badge-danger">Expired</span>';if(d<=60)return '<span class="badge badge-warn">Expires in '+d+' days</span>';return '<span class="badge badge-ok">Valid</span>';}
function showLogin(){$("login").style.display="grid";$("app").classList.remove("visible");}
function showApp(){$("login").style.display="none";$("app").classList.add("visible");render();}
function login(ev){ev.preventDefault();if($("pin").value.trim()!==PIN){$("login-error").textContent="Incorrect access code.";return;}sessionStorage.setItem(AUTH_KEY,"ok");showApp();}
function logout(){sessionStorage.removeItem(AUTH_KEY);showLogin();}
function setView(name,extra){view=name;if(name==="form"){stepIndex=0;editingId=extra&&extra.id?extra.id:null;draft=editingId?Object.assign(blankEmployee(),employees.find(e=>e.id===editingId)):blankEmployee();if(!draft.branch)draft.branch="Ahodwo, Kumasi";}if(name==="profile")editingId=extra.id;document.querySelectorAll(".nav button[data-view]").forEach(btn=>{btn.classList.toggle("active",btn.dataset.view===(name==="profile"||name==="form"?"directory":name));});render();}
function nextStaffNo(){const year=new Date().getFullYear();const nums=employees.map(e=>parseInt((e.staffNo||"").split("-").pop(),10)).filter(n=>!Number.isNaN(n));const next=(nums.length?Math.max.apply(null,nums):0)+1;return "LPC-"+year+"-"+String(next).padStart(3,"0");}
function saveDraft(){const form=$("staff-form");if(!form)return;const data=new FormData(form);for(const [k,v] of data.entries()){if(k==="documents")continue;draft[k]=v;}draft.documents=data.getAll("documents");draft.declared=form.querySelector("[name=declared]")?form.querySelector("[name=declared]").checked:draft.declared;}
function persistEmployee(){saveDraft();if(!draft.firstName||!draft.lastName){toast("First name and last name are required.");stepIndex=0;render();return;}const now=new Date().toISOString();if(!draft.id){draft.id="emp-"+Date.now();draft.staffNo=draft.staffNo||nextStaffNo();draft.createdAt=now;employees.push(draft);}else{const i=employees.findIndex(e=>e.id===draft.id);if(i>=0)employees[i]=draft;}draft.updatedAt=now;saveAll(employees);toast("Employee record saved.");setView("profile",{id:draft.id});}
function deleteEmployee(id){if(!confirm("Delete this employee record? This cannot be undone on this device."))return;employees=employees.filter(e=>e.id!==id);saveAll(employees);toast("Record deleted.");setView("directory");}
function exportJson(){const payload=JSON.stringify(employees,null,2);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([payload],{type:"application/json"}));a.download="lapetite-employee-records.json";a.click();}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw new Error("x");employees=data;saveAll(employees);toast("Records imported.");render();}catch{toast("Could not import that file.");}};reader.readAsText(file);}
function filtered(){const q=filters.q.toLowerCase();return employees.filter(e=>{const hay=[fullName(e),e.staffNo,e.jobTitle,e.phone,e.email,e.category].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;if(filters.category&&e.category!==filters.category)return false;if(filters.status&&e.status!==filters.status)return false;return true;}).sort((a,b)=>fullName(a).localeCompare(fullName(b)));}
function expiringSoon(){return employees.filter(e=>{const d=daysUntil(e.licenceExpiry);return d!==null&&d<=60;}).sort((a,b)=>daysUntil(a.licenceExpiry)-daysUntil(b.licenceExpiry));}
function renderDashboard(){const total=employees.length,pharmacists=employees.filter(e=>e.category==="Pharmacist").length,probation=employees.filter(e=>e.status==="Probation").length,exp=expiringSoon();return `<div class="topbar"><div><h2>Staff overview</h2><p>LaPetite Chemists Ltd · Plot 8 Block J, Ahodwo, Kumasi</p></div><div class="actions"><button class="btn btn-primary" onclick="setView('form')">Add employee</button></div></div><div class="grid stats"><div class="stat"><span>Employees on file</span><strong>${total}</strong></div><div class="stat"><span>Pharmacists</span><strong>${pharmacists}</strong></div><div class="stat"><span>On probation</span><strong>${probation}</strong></div><div class="stat"><span>Licences due / expired</span><strong>${exp.length}</strong></div></div><div class="panel" style="margin-top:16px"><h3>Recently updated</h3><p class="empty">Add the first employee to begin the Ahodwo register.</p></div>`;}
function renderDirectory(){const rows=filtered();return `<div class="topbar"><div><h2>Employee directory</h2><p>${rows.length} record${rows.length===1?"":"s"} shown</p></div><div class="actions"><button class="btn btn-primary" onclick="setView('form')">Add employee</button></div></div><div class="searchbar"><input placeholder="Search…" value="${filters.q.replace(/"/g,""")}" oninput="filters.q=this.value; render()"></div><div class="panel">${rows.length===0?'<p class="empty">No matching employees.</p>':'<div class="table-wrap"><table><thead><tr><th>Staff</th><th>Position</th><th>Status</th><th></th></tr></thead><tbody>'+rows.map(e=>`<tr><td>${fullName(e)}</td><td>${e.jobTitle||"—"}</td><td>${e.status}</td><td><button class="btn btn-ghost btn-sm" onclick="setView('profile',{id:'${e.id}'})">View</button></td></tr>`).join("")+'</tbody></table></div>'}</div>`;}
function input(name,label,type="text",extra=""){const val=draft[name]==null?"":String(draft[name]);return `<div class="field ${extra}"><label>${label}</label><input name="${name}" type="${type}" value="${val.replace(/"/g,""")}"></div>`;}
function select(name,label,options,extra=""){return `<div class="field ${extra}"><label>${label}</label><select name="${name}"><option value=""></option>${options.map(o=>`<option ${draft[name]===o?"selected":""}>${o}</option>`).join("")}</select></div>`;}
function area(name,label,extra=""){return `<div class="field ${extra}"><label>${label}</label><textarea name="${name}" rows="3">${(draft[name]||"").replace(/</g,"<")}</textarea></div>`;}
function renderStepFields(){const id=STEPS[stepIndex].id;if(id==="personal")return `<div class="form-grid">${input("firstName","First name")}${input("middleName","Middle name")}${input("lastName","Last name")}${input("dob","Date of birth","date")}${input("phone","Primary telephone","tel")}${input("email","Email address","email")}${select("marital","Marital status",MARITAL)}${input("address","Residential address","","span-2")}${input("digitalAddress","Digital address")}</div>`;if(id==="family")return `<div class="form-grid">${input("motherName","Mother’s full name","","span-2")}${input("fatherName","Father’s full name","","span-2")}</div>`;if(id==="education")return `<div class="form-grid">${select("education","Highest level of education",EDUCATION)}${input("course","Course / field of study","","span-2")}${input("institution","Institution","","span-2")}</div>`;if(id==="employment")return `<div class="form-grid">${input("jobTitle","Job title / position")}${input("startDate","Date employment started","date")}${select("status","Employment status",STATUSES)}${select("category","Professional category",CATEGORIES)}${input("licenceNo","Licence number")}${input("licenceExpiry","Licence expiry","date")}${input("branch","Branch")}${input("staffNo","Staff number")}</div>`;if(id==="payment")return `<div class="form-grid">${input("ghanaCard","Ghana Card number")}${input("ssnit","SSNIT number")}${input("bankName","Bank name")}${input("bankBranch","Bank branch")}${input("accountName","Account name")}${input("accountNo","Account number")}</div>`;if(id==="contacts")return `<div class="form-grid">${input("em1Name","Emergency contact name","","span-2")}${input("em1Rel","Relationship")}${input("em1Phone","Telephone","tel")}${input("kinName","Next of kin","","span-2")}${input("kinRel","Relationship")}${input("kinPhone","Telephone","tel")}</div>`;return `<div class="form-grid">${input("allergies","Known allergies","","span-2")}${area("medical","Medical information","span-2")}${input("hospital","Preferred hospital")}${input("bloodGroup","Blood group")}${area("notes","Additional information","span-2")}<div class="field span-2"><label class="checks"><input type="checkbox" name="declared" ${draft.declared?"checked":""}> I confirm the information is accurate.</label></div></div>`;}
function renderForm(){const title=editingId?"Edit employee":"New employee";return `<div class="topbar"><div><h2>${title}</h2><p>Confidential employee form</p></div></div><div class="steps">${STEPS.map((s,i)=>`<button class="step ${i===stepIndex?"on":i<stepIndex?"done":""}" onclick="saveDraft();stepIndex=${i};render()">${i+1}. ${s.title}</button>`).join("")}</div><form id="staff-form" class="panel" onsubmit="event.preventDefault(); persistEmployee()"><h3>${STEPS[stepIndex].title}</h3>${renderStepFields()}<div class="wizard-nav"><button type="button" class="btn btn-ghost" ${stepIndex===0?"disabled":""} onclick="saveDraft();stepIndex--;render()">Back</button><div style="display:flex;gap:8px"><button type="submit" class="btn btn-gold">Save record</button>${stepIndex<STEPS.length-1?`<button type="button" class="btn btn-primary" onclick="saveDraft();stepIndex++;render()">Next</button>`:""}</div></div></form>`;}
function pair(label,value){return `<dt>${label}</dt><dd>${value||"—"}</dd>`;}
function renderProfile(){const e=employees.find(x=>x.id===editingId);if(!e)return `<p class="empty">Record not found.</p>`;return `<div class="topbar"><div><h2>${fullName(e)}</h2><p>${e.staffNo} · ${e.jobTitle||"Unspecified role"}</p></div><div class="actions"><button class="btn btn-ghost" onclick="window.print()">Print</button><button class="btn btn-primary" onclick="setView('form',{id:'${e.id}'})">Edit</button><button class="btn btn-danger" onclick="deleteEmployee('${e.id}')">Delete</button></div></div><div class="panel"><dl class="kv">${pair("Telephone",e.phone)}${pair("Email",e.email)}${pair("Address",e.address)}${pair("Ghana Card",e.ghanaCard)}${pair("SSNIT",e.ssnit)}${pair("Licence",e.licenceNo)}</dl></div>`;}
function renderSettings(){return `<div class="topbar"><div><h2>Settings</h2><p>Records stay in this browser.</p></div></div><div class="panel"><div class="actions"><button class="btn btn-primary" onclick="exportJson()">Export records</button><label class="btn btn-ghost">Import records<input type="file" accept="application/json" hidden onchange="if(this.files[0]) importJson(this.files[0])"></label></div></div>`;}
function render(){const map={dashboard:renderDashboard,directory:renderDirectory,form:renderForm,profile:renderProfile,settings:renderSettings};$("content").innerHTML=(map[view]||renderDashboard)();}
window.addEventListener("DOMContentLoaded",()=>{$("login-form").addEventListener("submit",login);if(sessionStorage.getItem(AUTH_KEY)==="ok")showApp();else showLogin();});
